#Numpy in python

##Phase1
### Numpy basic commands

In [1]:
import numpy as np

arr_1d = np.array([1, 2, 3])
print("1d array:",arr_1d)



1d array: [1 2 3]


### Numpy array vs list


In [2]:
import time

import numpy as np

start =time.time()
py_list = [i*2 for i in range(100000)]
print("\nPython list execution time: ",time.time()-start)

start=time.time()
np_array=np.arange(10000)*2
print("Numpy array operation time: ",time.time()-start)


Python list execution time:  0.004769563674926758
Numpy array operation time:  0.0002906322479248047


### Matrix

In [3]:
zero=np.zeros((3,3))
print("\nZero array: \n",zero)

ones=np.ones((3,3))
print("\nOnes array: \n",ones)

full=np.full((3,3),5)
print("\nConstant element in array: \n",full)

random=np.random.random((3,3))
print("\nRandom elements in  array: \n",random)

sequence=np.arange(1,12,2)
print("\nSequenced Array: \n",sequence)



Zero array: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Constant element in array: 
 [[5 5 5]
 [5 5 5]
 [5 5 5]]

Random elements in  array: 
 [[0.75061756 0.61200099 0.66709169]
 [0.08562698 0.47568849 0.83628424]
 [0.01948201 0.86173369 0.83891872]]

Sequenced Array: 
 [ 1  3  5  7  9 11]


##

### Vector ,Matrix and tensor


In [4]:
vector=np.array([1,2,3,4])
print("Vector: \n",vector)

matrix=np.array([[1,2,3],
                [4,5,6]])
print("\nMatrix: \n",matrix)

tensor=np.array([ [[1,2],[3,4]],

                [[4,5],[6,7]]    ])
print("\nTensor: \n",tensor)


Vector: 
 [1 2 3 4]

Matrix: 
 [[1 2 3]
 [4 5 6]]

Tensor: 
 [[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]]


### Array properties

In [5]:
arr=np.array([[1,2,3],
              [4,5,6]])
print("Dimensions:",arr.ndim)
print("Size:",arr.size)
print("Shape:",arr.shape)
print("data-type:",arr.dtype)

Dimensions: 2
Size: 6
Shape: (2, 3)
data-type: int64


### Array reshaping

In [23]:
arr=np.arange(16)
print("\nOrigional array:\n",arr)

reshaped=arr.reshape((4,4))
print("\nReshaped array:\n",reshaped)

flatten=arr.flatten()
print("\nFlatten array:\n",flatten)

#return view, instead of copy
raveled=arr.ravel()
print("\nravled array:\n",raveled)

transpose=reshaped.T
print("\nTransposed array:\n",transpose)


Origional array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

Reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Flatten array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

ravled array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

Transposed array:
 [[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]



##Phase 2
### Slicing


In [34]:
arr=np.arange(12)
print("Print Array:",arr)
print("\n Basic Slicing:",arr[2:9])
print("\n Step Slicing:",arr[1:10:2])
print("\n Reversed using Negetaive idx Slicing:",arr[::-1]) #(from start::last)
print("\n Negetaive idx Slicing:",arr[-1])

Print Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Basic Slicing: [2 3 4 5 6 7 8]

 Step Slicing: [1 3 5 7 9]

 Reversed using Negetaive idx Slicing: [11 10  9  8  7  6  5  4  3  2  1  0]

 Negetaive idx Slicing: 11


### 2D matrices

In [45]:
arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print("2D matrix\n",arr_2d)
print("\nSpecific Element:",arr_2d[2,1])
print("\nEntire Row:",arr_2d[0])
                      #all rows->:,columns,
print("\nEntire column:",arr_2d[:,1])




2D matrix
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Specific Element: 8

Entire Row: [1 2 3]

Entire column: [2 5 8]
