# Numpy in python

## Basics
### Numpy basic commands

In [1]:
%pip install numpy
import numpy as np

arr_1d = np.array([1, 2, 3])
print("1d array:",arr_1d)



Note: you may need to restart the kernel to use updated packages.
1d array: [1 2 3]


### Numpy array vs list


In [2]:
import time

import numpy as np

start =time.time()
py_list = [i*2 for i in range(100000)]
print("\nPython list execution time: ",time.time()-start)

start=time.time()
np_array=np.arange(10000)*2
print("Numpy array operation time: ",time.time()-start)


Python list execution time:  0.0068967342376708984
Numpy array operation time:  0.00015878677368164062


### Matrix

In [3]:
zero=np.zeros((3,3))
print("\nZero array: \n",zero)

ones=np.ones((3,3))
print("\nOnes array: \n",ones)

full=np.full((3,3),5)
print("\nConstant element in array: \n",full)


print("\nItentity matrix :\n",IdentityMat:=np.eye(3))

random=np.random.random((3,3))
print("\nRandom elements in  array: \n",random)

sequence=np.arange(1,12,2)
print("\nSequenced Array: \n",sequence)



Zero array: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Constant element in array: 
 [[5 5 5]
 [5 5 5]
 [5 5 5]]

Itentity matrix :
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random elements in  array: 
 [[0.01594341 0.56522145 0.66879461]
 [0.86685375 0.3686663  0.01388066]
 [0.61556088 0.7945512  0.08487803]]

Sequenced Array: 
 [ 1  3  5  7  9 11]


## Mediate

### Vector ,Matrix and tensor


In [4]:
vector=np.array([1,2,3,4])
print("Vector: \n",vector)

matrix=np.array([[1,2,3],
                [4,5,6]])
print("\nMatrix: \n",matrix)

tensor=np.array([ [[1,2],[3,4]],

                [[4,5],[6,7]]    ])
print("\nTensor: \n",tensor)


Vector: 
 [1 2 3 4]

Matrix: 
 [[1 2 3]
 [4 5 6]]

Tensor: 
 [[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]]


### Array properties

In [5]:
arr=np.array([[1.5,2.7,3.4],
              [4,5.2,6]])
print("Dimensions:",arr.ndim)
print("Size:",arr.size) #totalm num of elements
print("Shape:",arr.shape)
print("data-type:",arr.dtype)
print("Conversion into float:\n",arr:=arr.astype(int))

Dimensions: 2
Size: 6
Shape: (2, 3)
data-type: float64
Conversion into float:
 [[1 2 3]
 [4 5 6]]


### Array operation

In [6]:
print("\nadditon\n",arr+2)
print("\nSub\n",arr-1)
print("\nMul\n",arr*2)
print("\nPow\n",arr**2)


additon
 [[3 4 5]
 [6 7 8]]

Sub
 [[0 1 2]
 [3 4 5]]

Mul
 [[ 2  4  6]
 [ 8 10 12]]

Pow
 [[ 1  4  9]
 [16 25 36]]


### Aggregate Functions

In [7]:
arr=np.arange(10,60,10)#(start,stop,step)
print("\nOrigional array:\n",arr)
print(np.sum(arr))
print("Variation :",np.var(arr))
print(np.min(arr))
print(np.max(arr))
print("Standard deviation :",np.std(arr))




Origional array:
 [10 20 30 40 50]
150
Variation : 200.0
10
50
Standard deviation : 14.142135623730951


### Array reshaping

In [8]:
arr=np.arange(16)
print("\nOrigional array:\n",arr)

reshaped=arr.reshape((4,4))
print("\nReshaped array:\n",reshaped)

flatten=arr.flatten()
print("\nFlatten array:\n",flatten)

#return view, instead of copy
raveled=arr.ravel()
print("\nravled array:\n",raveled)

transpose=reshaped.T
print("\nTransposed array:\n",transpose)


Origional array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

Reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Flatten array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

ravled array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

Transposed array:
 [[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


### Slicing

In [9]:
arr=np.arange(12)
print("Print Array:",arr)
print("\n Basic Slicing:",arr[2:9])
print("\n Step Slicing:",arr[1:10:2])
print("\n Reversed using Negetaive idx Slicing:",arr[::-1]) #(from start::last)
print("\n Negetaive idx Slicing:",arr[-1])

Print Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Basic Slicing: [2 3 4 5 6 7 8]

 Step Slicing: [1 3 5 7 9]

 Reversed using Negetaive idx Slicing: [11 10  9  8  7  6  5  4  3  2  1  0]

 Negetaive idx Slicing: 11


### 2D matrices

In [10]:
arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print("2D matrix\n",arr_2d)
print("\nSpecific Element:",arr_2d[2,1])
print("\nEntire Row:",arr_2d[0])
                      #all rows->:,columns,
print("\nEntire column:",arr_2d[:,1])




2D matrix
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Specific Element: 8

Entire Row: [1 2 3]

Entire column: [2 5 8]


### Sorting


In [11]:
unsorted=np.array([5,1,6,8,2,9,3])
print("Sorted 1D Array:",np.sort(unsorted))

arr2D=np.array([[5,3],
                [2,1],
                [3,1]])
print("\nSorted 2D array:\n",np.sort(arr2D,axis=0)) #column wise sorted

print("\nSorted 2D array:\n",np.sort(arr2D,axis=1)) #row wise sorted

Sorted 1D Array: [1 2 3 5 6 8 9]

Sorted 2D array:
 [[2 1]
 [3 1]
 [5 3]]

Sorted 2D array:
 [[3 5]
 [1 2]
 [1 3]]


## Filter


In [12]:
num=np.array([1,2,3,4,5,6,7,8,9,10])
even=num[num%2==0]
print(even)

[ 2  4  6  8 10]


### Filter using Mask

In [13]:
odd=num%2!=0
print(num[odd])

[1 3 5 7 9]


### Fancy Indecies and np.where()

In [14]:
idx=[0,1,-1]
print(num[idx])

where=np.where(num>5)
print("NP where",num[where])

[ 1  2 10]
NP where [ 6  7  8  9 10]


In [15]:

                           #condition true  |condition false then returns
               #(condition,returns 1st expression,  2nd expression)
conditional_arr = np.where(num<5,"true","false")
print(conditional_arr)

['true' 'true' 'true' 'true' 'false' 'false' 'false' 'false' 'false'
 'false']


## Adding and Removing

### Compatibility test


In [16]:
a=np.array([1,2,5])
b=np.array([8,5,9,6])
c=np.array([7,2,3])
print("is A's shape = B's shape: ",a.shape== b.shape)
print("is A's shape = c's shape: ",a.shape== c.shape)


is A's shape = B's shape:  False
is A's shape = c's shape:  True


### Insertion

In [17]:
arr=np.array([10,20,30])
print("Insertion in 1D: ",np.insert(arr,3,40))

arr_2d=np.array([[1,2],
                 [5,6],])
# shape of the given array should be compatible for newly added elements
print("Insertion in 2D axis 0:\n",np.insert(arr_2d,1,[3,4],axis=0))

print("Insertion in 2D axis 1 :\n",np.insert(arr_2d,1,[3,4],axis=1))

print("Append: ",np.append(arr,[1,2]))

print("concatenate of two array",np.concatenate((arr,arr2:=np.array([40,50,60])),axis=0))

Insertion in 1D:  [10 20 30 40]
Insertion in 2D axis 0:
 [[1 2]
 [3 4]
 [5 6]]
Insertion in 2D axis 1 :
 [[1 3 2]
 [5 4 6]]
Append:  [10 20 30  1  2]
concatenate of two array [10 20 30 40 50 60]


### Adding rows or column

In [18]:
original_arr=np.array([[1,2],
                       [5,6],
                       [9,10]])
new_row=np.array([12,13])
        #Vertical stack < axis0
new_col=np.array([[3],
                  [7],
                  [11],
                  [14]])

print("\nwith new row added\n",withNewRow:=np.vstack((original_arr,new_row)))
            #horizontal stack < axis 1

print("\nwith new col added\n",withNewCol:=np.hstack((withNewRow,new_col)))



with new row added
 [[ 1  2]
 [ 5  6]
 [ 9 10]
 [12 13]]

with new col added
 [[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [12 13 14]]


### Deletion

In [19]:
deleted=np.delete(withNewRow,0) #removes after fallterning the array
print("After deletion\n",deleted)

arr=np.array([[1, 2, 3],
			  [5, 6, 7],
			  [9, 10, 11],
			  [12, 13, 14]])
print("Deletion in 2D:\n",np.delete(arr,1,axis=0))
print("Deletion in 2D with axis 1:\n",np.delete(arr,2,axis=1))


After deletion
 [ 2  5  6  9 10 12 13]
Deletion in 2D:
 [[ 1  2  3]
 [ 9 10 11]
 [12 13 14]]
Deletion in 2D with axis 1:
 [[ 1  2]
 [ 5  6]
 [ 9 10]
 [12 13]]


### Spliting

In [20]:
arr=np.array([[1, 2, 3],
			  [5, 6, 7],
			  [9, 10, 11],
			  [12, 13, 14]])
print("Split():",np.split(arr,2))
##vsplit=p.split(arr,3,axis=0))
print("\nvsplit():",np.vsplit(arr,4))
#hsplit=p.split(arr,3,axis=1))
print("hsplit():\n",np.hsplit(arr,3))


Split(): [array([[1, 2, 3],
       [5, 6, 7]]), array([[ 9, 10, 11],
       [12, 13, 14]])]

vsplit(): [array([[1, 2, 3]]), array([[5, 6, 7]]), array([[ 9, 10, 11]]), array([[12, 13, 14]])]
hsplit():
 [array([[ 1],
       [ 5],
       [ 9],
       [12]]), array([[ 2],
       [ 6],
       [10],
       [13]]), array([[ 3],
       [ 7],
       [11],
       [14]])]
